name = "sheet2json-worker"
main = "index.js"
compatibility_date = "2024-08-06"
# type = "webpack"
# account_id = ""
# route = ""
# zone_id = ""
# vars = {DOC_ID = "1hzo3jlSnY3BcleC4Xt0iINefouXSoShjcZlprU4Ndmc",SHEET_NAME = "Sheet1",TTL = "5"}